kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-deploy
  namespace: pv
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/www/html
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pvc1
