kind: Namespace
apiVersion: v1
metadata:
  name: nginx

---

kind: Pod
apiVersion: v1
metadata: 
  name: nginx-pod
  namespace: nginx
  labels: 
    app: nginx
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports: 
    - containerPort: 80

---

kind: Service
apiVersion: v1
metadata:
  name: nginx-svc
  namespace: nginx
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
