kind: Namespace
apiVersion: v1
metadata:
  name: mysql

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: mysql-configmap
  namespace: mysql
data:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: devops
---

kind: Secret
apiVersion: v1
metadata: 
  name: mysql-secret
  namespace: mysql
data:
  MYSQL_ROOT_PASSWORD: cm9vdAo=
  MYSQL_DATABASE: ZGV2b3BzCg==
---

kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: mysql-statefulset
  namespace: mysql
  labels:
    app: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql-service
  template:
    metadata: 
      name: mysql-template
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-container
        image: mysql
        env:
        #- name: MYSQL_ROOT_PASSWORD
        #  value: root
        #- name: MYSQL_DATABASE
        #  value: devops
        
        #configMap
        #- name: MYSQL_ROOT_PASSWORD
        #  valueFrom:
        #    configMapKeyRef:
        #      name: mysql-configmap
        #      key: MYSQL_ROOT_PASSWORD
        #- name: MYSQL_DATABASE
        #  valueFrom:
        #    configMapKeyRef:
        #      name: mysql-configmap
        #      key: MYSQL_DATABASE

        #secret
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_DATABASE
        ports: 
        - containerPort: 80
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi

---

kind: Service
apiVersion: v1
metadata: 
  name: mysql-service
  namespace: mysql
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  clusterIP: None
